# Generated by Django 3.2.4 on 2021-06-23 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_numb', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servis_order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID заказа', primary_key=True, serialize=False)),
                ('Servis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.services')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
            ],
        ),
    ]
