# Generated by Django 3.2.4 on 2021-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210623_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis_order',
            old_name='Servis',
            new_name='servis',
        ),
    ]
