# Generated by Django 3.2.4 on 2021-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_servis_servis_order_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis_order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
