# Generated by Django 3.2.4 on 2021-06-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_servis_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='First_name',
            field=models.CharField(help_text='Имя заказчика', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Last_name',
            field=models.CharField(help_text='Фамилия заказчика', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone_numb',
            field=models.CharField(help_text='Номер заказчика', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_id',
            field=models.CharField(help_text='Id фото для отображения в карусели в ВК', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='servis_name',
            field=models.CharField(help_text='Название услуги', max_length=30),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='Services',
            field=models.ForeignKey(help_text='Заказаная услуга', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.services'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='cust',
            field=models.ForeignKey(help_text='Данные заказчика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='date',
            field=models.DateField(blank=True, help_text='Дата заказа', null=True),
        ),
    ]
