# Generated by Django 3.2.4 on 2021-07-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_servis_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis_order',
            old_name='cust',
            new_name='заказчик',
        ),
    ]
