# Generated by Django 3.2.4 on 2021-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210708_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis_order',
            name='Дата',
            field=models.DateField(blank=True, help_text='Дата заказа', null=True, verbose_name='Date'),
        ),
    ]
