# Generated by Django 3.2.4 on 2021-07-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_servis_order_дата'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis_order',
            old_name='Услуга',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='servis_order',
            old_name='Дата',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='servis_order',
            old_name='Статус',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='servis_order',
            name='Заказчик',
        ),
        migrations.AddField(
            model_name='servis_order',
            name='cust',
            field=models.ForeignKey(help_text='Данные заказчика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer', verbose_name='Название'),
        ),
    ]
