# Generated by Django 3.2.4 on 2021-07-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210708_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis_order',
            name='Services',
            field=models.ForeignKey(help_text='Заказаная услуга', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='cust',
            field=models.ForeignKey(help_text='Данные заказчика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='date',
            field=models.DateField(blank=True, help_text='Дата заказа', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='status',
            field=models.CharField(blank=True, choices=[('Н', 'Новый'), ('Р', 'В работе'), ('В', 'Выполнен')], default='Н', help_text='Статус заказа', max_length=1, verbose_name='Статус'),
        ),
    ]
