# Generated by Django 3.2.4 on 2021-07-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servis_order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
