# Generated by Django 3.2.4 on 2021-07-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210708_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['Phone_numb'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчик'},
        ),
        migrations.AlterModelOptions(
            name='servis_order',
            options={'ordering': ('date',), 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
