# Generated by Django 3.2.4 on 2021-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210709_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servis_order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата заказа', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата заказа', null=True, verbose_name='Дата'),
        ),
    ]
