# Generated by Django 3.2.4 on 2021-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210709_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis_order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время поступления заказа'),
        ),
        migrations.AlterField(
            model_name='servis_order',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время обновления', null=True, verbose_name='Время обновления'),
        ),
    ]
