# Generated by Django 3.2.4 on 2021-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_servis_order_publish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servis_order',
            name='publish_at',
        ),
    ]
