# Generated by Django 3.2.4 on 2021-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_servis_order_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis_order',
            name='publish_at',
            field=models.DateTimeField(help_text='Время обновления', null=True, verbose_name='Время обновления'),
        ),
    ]
