# Generated by Django 3.2.4 on 2021-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_servis_order_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis_order',
            name='status',
            field=models.CharField(blank=True, choices=[('Н', 'Новый'), ('Р', 'В работе'), ('В', 'Выполнен')], default=False, help_text='Статус заказа', max_length=1, verbose_name='Статус'),
        ),
    ]
